version: '3.8'
services:
  kubernetes-masterclass-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kubernetes-masterclass
    ports:
      - "15432:5432"
