version: '3.8'
services:
  kubernetes-masterclass-api:
    container_name: kubernetes-masterclass-api-container
    build:
      context: springboot-project
      dockerfile: Dockerfile.layered
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://kubernetes-masterclass-db:5432/kubernetes-masterclass
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "18080:8080"
    restart: always
    depends_on:
      - kubernetes-masterclass-db

  kubernetes-masterclass-ui:
    container_name: kubernetes-masterclass-ui-container
    build:
      context: nextjs-project
      dockerfile: Dockerfile
    ports:
      - "13000:3000"
    environment:
      SERVER_SIDE_API_BASE_URL: http://kubernetes-masterclass-api:8080
      CLIENT_SIDE_API_BASE_URL: http://localhost:18080
