apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-masterclass-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-masterclass-api-pod
  template:
    metadata:
      labels:
        app: kubernetes-masterclass-api-pod
    spec:
      containers:
      - name: kubernetes-masterclass-api
        image: iboukhenna/kubernetes-masterclass
        ports:
          - containerPort: 8080
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8s
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: kubernetes-masterclass-config
                key: postgres_host
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: kubernetes-masterclass-config
                key: postgres_port
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: kubernetes-masterclass-secret
                key: postgres_username
          - name: DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: kubernetes-masterclass-secret
                key: postgres_password
          - name: DB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: kubernetes-masterclass-config
                key: postgres_dbname
