apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-masterclass-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-masterclass-api-pod
  template:
    metadata:
      labels:
        app: kubernetes-masterclass-api-pod
    spec:
      containers:
      - name: kubernetes-masterclass-api
        image: iboukhenna/kubernetes-masterclass
        ports:
          - containerPort: 8080
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8s
